### PR TITLE
Cleaned up the navbar

### PR DESCRIPTION
**Pull request by hopieyimmie**
Removed 'Home' and 'SignUp' Links at the top of the NavBar

### CODE REVIEW

**Review by NickAspiras — APPROVED** [review]
Commenting the code was very helpful and looks great!

**Review by nickambrose7 — APPROVED** [review]
LGTM!

**Review by hsterry — CHANGES_REQUESTED** [review]
It doesn't look like the most updated version of the code was pulled before the PR. Might be deprecated

**Review by hsterry — CHANGES_REQUESTED** [review]
It doesn't look like the most updated version of the code was pulled before the PR. Might be deprecated

**Pull request closed without merging**
