### PR TITLE
Routing to single movie page, style clean up, minor code clean up

### PR DESCRIPTION
**Pull request by nickambrose7**
We now have routing so that when a user clicks on a movie, they will be directed to the correct single movie page for that movie. I also did a rework of the review section, mostly just styling changes. There was some commented code that I just removed to start chipping away at our code clean-up task.

Let me know what you guys think!

### CODE REVIEW

**Review by NickAspiras — APPROVED** [review]
Looks great Nick! Good work on getting this all together!

**Review by hopieyimmie — APPROVED** [review]
Looks great to me! The routing single movie should also work for when a user clicks on a movie after adding it to a watchlist too! Once I get my watchlist working, I can figure out the routing but it shouldn't cause issues or be too difficult. Great work!

**Comment by nickambrose7** [comment]
> Looks great to me! The routing single movie should also work for when a user clicks on a movie after adding it to a watchlist too! Once I get my watchlist working, I can figure out the routing but it shouldn't cause issues or be too difficult. Or when this is merged/approved, I can just pull from yours and get the routing to work with the watchlist. Great work!

Thanks for looking at that. If you need any help with routing on the watchlist, always feel free to reach out!

**Comment by nickambrose7** [comment]
> Looks great Nick! Good work on getting this all together!

Thanks Nick!

**Review by hsterry — APPROVED** [review]
Great work on this! I think this is really important functionality and I'm excited about the modularity of it.

**Comment by nickambrose7** [comment]
> Great work on this! I think this is really important functionality and I'm excited about the modularity of it.

Thanks!

**Pull request merged**
