### PR TITLE
Nick a 1

### PR DESCRIPTION
**Pull request by NickAspiras**
Created the Admin page, which includes edit functionality, as well as immediate action if the current user is deselected as admin
Created the Profile page, which includes functionality to go to the Admin page (if the current user is an admin), and edit their profile attributes (includes name, email, and isAdmin)

### CODE REVIEW

**Review by hsterry — APPROVED** [review]
This looks great! Also great work getting the CI build to pass.

**Comment by hopieyimmie** [comment]
This looks great!

**Review by hopieyimmie — APPROVED** [review]
This looks great, Nick! Good job!

**Review by nickambrose7 — APPROVED** [review]
Looks good to me! I do see you left some code commented out. Completely fine with me if you want to leave that right now, but we should definitely make note of cleaning that up before our final build. Great work Nick!

**Pull request merged**
